### ISSUE TITLE
5.0.8.1 to-do's

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/mine-issues#69]
- [x] merge 5.0.8 in
- [x] add Region extends SequenceFeature, + isCircular attribute, GFF type region
- [x] add PseudoGene extends SequenceFeature SO:0000336, GFF type pseudogene
- [x] Expression changes
  - [x] lis-expression
  - [x] ExpressionSample BioEntity -> root class (not even Annotatable)
  - [x] ExpressionCollectionValidator.java
  - [x] file formats - samples.tsv.gz
    - [x] Cajanus/cajan/expression/ICPL87119.gnm1.ann1.expr.4H6Z/
    - [x] Cicer/arietinum/expression/CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018/
    - [x] Cicer/arietinum/expression/CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018/
    - [x] Cicer/arietinum/expression/CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018/
    - [x] Cicer/arietinum/expression/CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a/
    - [x] Cicer/arietinum/expression/CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b/
    - [x] Cicer/arietinum/expression/ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013/
    - [x] Glycine/max/expression/Wm82.gnm2.ann1.expr.G7ZY/
    - [x] Medicago/truncatula/expression/A17_HM341.gnm4.ann2.expr.RLZY/
    - [x] Phaseolus/vulgaris/expression/G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014/
    - [x] Vigna/unguiculata/expression/IT97K-499-35.gnm1.ann1.expr.BWH5/

**Comment by sammyjava** [comment]
```
/data/v2/Cajanus/cajan/expression/
└── ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017
    ├── cajca.ICPL87119.gnm1.ann1.expr.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.values.tsv.gz
    ├── cajca.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.metadata.xlsx
    ├── cajca.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.obo.tsv.gz
    ├── cajca.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.samples.tsv.gz
    ├── CHANGES.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.txt
    └── README.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.yml
/data/v2/Cicer/arietinum/expression/
├── CDCFrontier.gnm1.ann1.expr.C14F
│   ├── CHANGES.CDCFrontier.gnm1.ann1.expr.C14F.txt
│   ├── cicar.CDCFrontier.gnm1.ann1.expr.C14F.metadata.xlsx
│   ├── cicar.CDCFrontier.gnm1.ann1.expr.C14F.values.tsv.gz
│   └── README.CDCFrontier.gnm1.ann1.expr.C14F.yml
├── CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018.yml
├── CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018.yml
├── CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018.yml
├── CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a.yml
├── CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b.yml
└── ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013
    ├── cicar.ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013.obo.tsv.gz
    ├── cicar.ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013.samples.tsv.gz
    ├── cicar.ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013.values.tsv.gz
    ├── metadata.xlsx
    └── README.ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013.yml
/data/v2/Glycine/max/expression/
└── Wm82.gnm2.ann1.expr.Wm82.Libault_Farmer_2010
    ├── glyma.Wm82.gnm2.ann1.expr.Wm82.gnm2.ann1.expr.Wm82.Libault_Farmer_2010.obo.tsv.gz
    ├── glyma.Wm82.gnm2.ann1.expr.Wm82.gnm2.ann1.expr.Wm82.Libault_Farmer_2010.samples.tsv.gz
    ├── glyma.Wm82.gnm2.ann1.expr.Wm82.gnm2.ann1.expr.Wm82.Libault_Farmer_2010.values.tsv.gz
    └── README.Wm82.gnm2.ann1.expr.Wm82.Libault_Farmer_2010.yml
/data/v2/Medicago/truncatula/expression/
└── A17_HM341.gnm4.ann2.expr.He_Vagner_2009
    ├── medtr.A17_HM341.gnm4.ann2.expr.He_Vagner_2009.obo.tsv.gz
    ├── medtr.A17_HM341.gnm4.ann2.expr.He_Vagner_2009.samples.tsv.gz
    ├── medtr.A17_HM341.gnm4.ann2.expr.He_Vagner_2009.values.tsv.gz
    └── README.A17_HM341.gnm4.ann2.expr.He_Vagner_2009.yml
/data/v2/Phaseolus/vulgaris/expression/
└── G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014
    ├── phavu.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.obo.tsv.gz
    ├── phavu.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.samples.tsv.gz
    ├── phavu.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.values.tsv.gz
    └── README.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.yml
/data/v2/Vigna/unguiculata/expression/
└── IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016
    ├── CHANGES.IT97K-499-35.gnm1.ann1.expr.BWH5.txt
    ├── README.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.yml
    ├── vigun.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.metadata.xlsx.gz
    ├── vigun.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.obo.tsv.gz
    ├── vigun.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.samples.tsv.gz
    └── vigun.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.values.tsv.gz
```

**Comment by sammyjava** [comment]
Including yet-to-be published cicar collections:
```
Cajanus/cajan/expression/
└── ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017
    ├── cajca.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.metadata.xlsx.gz
    ├── cajca.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.obo.tsv.gz
    ├── cajca.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.samples.tsv.gz
    ├── cajca.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.values.tsv.gz
    ├── CHANGES.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.txt
    └── README.ICPL87119.gnm1.ann1.expr.ICPL87119.Pazhamala_Purohit_2017.yml
Cicer/arietinum/expression/
├── CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018.yml
├── CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018.yml
├── CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018.yml
├── CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a.yml
├── CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b.obo.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b.samples.tsv.gz
│   ├── cicar.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b.values.tsv.gz
│   └── README.CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b.yml
└── ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013
    ├── cicar.ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013.obo.tsv.gz
    ├── cicar.ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013.samples.tsv.gz
    ├── cicar.ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013.values.tsv.gz
    ├── metadata.xlsx
    └── README.ICC4958.gnm2.ann1.expr.ICC4958.Singh_Garg_2013.yml
Glycine/max/expression/
└── Wm82.gnm2.ann1.expr.Wm82.Libault_Farmer_2010
    ├── glyma.Wm82.gnm2.ann1.expr.Libault_Farmer_2010.obo.tsv.gz
    ├── glyma.Wm82.gnm2.ann1.expr.Libault_Farmer_2010.samples.tsv.gz
    ├── glyma.Wm82.gnm2.ann1.expr.Libault_Farmer_2010.values.tsv.gz
    └── README.Wm82.gnm2.ann1.expr.Wm82.Libault_Farmer_2010.yml
Medicago/truncatula/expression/
└── A17_HM341.gnm4.ann2.expr.He_Vagner_2009
    ├── medtr.A17_HM341.gnm4.ann2.expr.He_Vagner_2009.obo.tsv.gz
    ├── medtr.A17_HM341.gnm4.ann2.expr.He_Vagner_2009.samples.tsv.gz
    ├── medtr.A17_HM341.gnm4.ann2.expr.He_Vagner_2009.values.tsv.gz
    └── README.A17_HM341.gnm4.ann2.expr.He_Vagner_2009.yml
Phaseolus/vulgaris/expression/
└── G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014
    ├── phavu.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.obo.tsv.gz
    ├── phavu.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.samples.tsv.gz
    ├── phavu.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.values.tsv.gz
    └── README.G19833.gnm1.ann1.expr.Negro_jamapa.ORourke_Iniguez_2014.yml
Vigna/unguiculata/expression/
└── IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016
    ├── CHANGES.IT97K-499-35.gnm1.ann1.expr.BWH5.txt
    ├── README.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.yml
    ├── vigun.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.metadata.xlsx.gz
    ├── vigun.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.obo.tsv.gz
    ├── vigun.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.samples.tsv.gz
    └── vigun.IT97K-499-35.gnm1.ann1.expr.Yao_Jiang_2016.values.tsv.gz
```
